# -*- coding: utf-8 -*-
"""week3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tsuQipqaSlyOK49K9txgvFhbAHj9phpb
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

import warnings
warnings.filterwarnings("ignore")

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("marketing_campaign.csv", sep="\t")

df.head()

df = df.dropna()

df["Age"] = 2025 - df["Year_Birth"]

df["Total_Spending"] = (
    df["MntWines"] +
    df["MntFruits"] +
    df["MntMeatProducts"] +
    df["MntFishProducts"] +
    df["MntSweetProducts"] +
    df["MntGoldProds"]
)

features = [
    "Income",
    "Age",
    "Kidhome",
    "Teenhome",
    "Recency",
    "MntWines",
    "MntFruits",
    "MntMeatProducts",
    "MntFishProducts",
    "MntSweetProducts",
    "MntGoldProds",
    "Total_Spending"
]

X = df[features]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=0.95)

X_pca = pca.fit_transform(X_scaled)

print("Original Shape:", X_scaled.shape)
print("Reduced Shape:", X_pca.shape)

wcss = []

for k in range(2,11):
    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    model.fit(X_pca)

    wcss.append(model.inertia_)

plt.figure(figsize=(8,5))

plt.plot(range(2,11), wcss, marker="o")

plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.title("Elbow Method")

plt.show()

scores = []

for k in range(2,11):

    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = model.fit_predict(X_pca)

    score = silhouette_score(
        X_pca,
        labels
    )

    scores.append(score)

plt.figure(figsize=(8,5))

plt.plot(range(2,11), scores, marker="o")

plt.xlabel("Clusters")
plt.ylabel("Silhouette Score")

plt.show()

kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

df["Cluster"] = kmeans.fit_predict(X_pca)

pca2 = PCA(n_components=2)

X_2D = pca2.fit_transform(X_scaled)

plot_df = pd.DataFrame(X_2D, columns=["PC1","PC2"])

plot_df["Cluster"] = df["Cluster"]

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=plot_df,
    x="PC1",
    y="PC2",
    hue="Cluster",
    palette="Set2"
)

plt.title("Customer Segmentation using PCA + KMeans")

plt.show()

cluster_summary = df.groupby("Cluster")[[
    "Income",
    "Age",
    "Total_Spending"
]].mean()

cluster_summary

df['Cluster'].value_counts()

cluster_summary